### ISSUE TITLE
variable alpha damping

### ISSUE THREAD

**Issue by dwille** [groundcherry/bluebottle#13]
bluebottle_kernel.cu // collision_walls:
-- variable alpha damping is only implemented for east and west walls

**Comment by dwille** [comment]
This was intentional. Will be fixed presently

**Comment by asiera** [comment]
Dan - I was just looking at the wall collisions, and I'm actually pretty sure it is implemented for all walls. Would you verify this for me, just as a sanity check?

**Comment by dwille** [comment]
I still only see it implemented for east/west. For these, you set (see 2850 and 2856 for east wall)
parts[i].St = -1 if h < hN && h > 0
and
parts[i].St = ... if h < 0 && parts[i].St == -1

for south, north, top, and bottom you perform the first of the operations, but not the second.

**Comment by asiera** [comment]
Yikes. Thank you. I am patching it now.
