### ISSUE TITLE
flow.config domain size

### ISSUE THREAD

**Issue by dwille** [groundcherry/bluebottle#14]
Simulations blow up for certain domain sizes. For the same parameters, a simulation that goes from 0 to 30 will blow up, but a simulation that goes from -15 to 15 will not. The simulation fails by time step size.

It is currently unclear how symmetric the simulation has to be to produce this error. I've attempted using -1 to 29 and it failed, but -10 to 20 did not.

Steps to reproduce:
-- Launch a case with an asymmetric domain

**Comment by ajsierakowski** [comment]
Fixed in f51301bd4aa492f3489cd402101d5e63ce6d989b
