### ISSUE TITLE
Error while compiling BlueBottle

### ISSUE THREAD

**Issue by Alwidron** [groundcherry/bluebottle#2]
Hello, my name is Álvaro Vidal and I wanted to ask you about some points of this great tool.
 First of all, I installed the requirements with this versions:
Ubuntu 12.04 64bits
CUDA 5.5
nVidia Driver 346.35
OpenMPI 1.8.4
CUSP 0.4.0
HDF5 (compiled with gcc and fortran)
CGNS 3.2.1 (compiled with HDF5 and MPI)

After that, I filled the Makefile and try to compile, but I got the next sentences:

/usr/local/cuda-5.5/bin -arch=sm_30 -Xcompiler -fopenmp -m64 -DDOUBLE -O2 -dc src/cuda_bluebottle.cu -I /home/alvaro/NVIDIA_CUDA-5.5_Samples/NVIDIA_CUDA-5.5_Samples/common/inc -I /usr/local/openmpi-1.8.4/include -I /usr/local/include -o src/cuda_bluebottle.o

make: execvp: /usr/local/cuda-5.5/bin: Permission denied
make: *** [src/cuda_bluebottle.o] Error 127

And the compilation is aborted. There is anything that I didn't notice and did wrong? Because  I don't understand the "permission denied" while I'm using the sudo command

And second, could you tell me the versions (with the flags used) of the dependencies used in your main PC (I have a GTX 660)?

Best Regards

**Comment by Alwidron** [comment]
My bad, I called the directory of nvcc instedd of the binary itself.

Anyway, could I know the perfect versions with the recommended flags of the dependencies? Thank very much

Best Regards

**Comment by asiera** [comment]
Álvaro,

I'm glad you were able to get Bluebottle to compile. Below you will find the versions that I have tested most recently. It would be nice to build a list of dependency versions that are known to work well. Have you been able to run Bluebottle using the dependencies that you have installed? 

The dependencies that I have used most recently:
CUDA: 5.5
GCC: 4.7.2
CUSP: 0.3.1
OMPI: 1.4.5
HDF5: 1.8.13
CGNS: 3.2.1

I would need some time to reinstall the libraries to determine the exact flags that I used during compilation. Is this information crucial to you?

Cheers,

Adam

**Comment by Alwidron** [comment]
Hello Adam,

Thank you very much for the early answer and yes, I have been able to install it and run it with good results. I didn't tell before but the version of HDF5 used by me was 1.8.14.

It's not at all crucial to me, just to know in case something goes wrong, what is the possible solution.

Best Regards,
Álvaro

**Comment by asiera** [comment]
Álvaro,

This is good news. I'm pleased that you've had satisfactory results thus far. Since the installation of dependencies is often machine dependent, I'd prefer to steer clear of publishing installation procedures for them. Anyway, it sounds as though you've been able to make everything work properly on your own, confirming that--for at least a small sample size--users seem to be able to navigate this dependency installation without too much direction on my part.

I will now mark this issue closed. I encourage you to keep in touch as you begin using Bluebottle.

Best,

Adam
