### ISSUE TITLE
Is there a way to impose Stokes flow?

### ISSUE THREAD

**Issue by Alwidron** [groundcherry/bluebottle#27]
Hi,
I'm trying to reproduce a Stokes flow mainly by imposing small reynols flow numbers. So my question is, is there a way to really impose this kind of flow in bluebottle?
Thank you very much
Álvaro

**Comment by asiera** [comment]
Hi Álvaro,

Yes, I believe this can be accomplished rather simply, though it would require some testing to ensure we're getting acceptable accuracy.

First a question for you: Are you looking for true, theoretical, zero-Reynolds-number Stokes flow, or are you looking for very-small-Reynolds-number Stokes flow?

Adam

**Comment by Alwidron** [comment]
Hi Adam,
Both of them, at first I'm looking for a theoretical approach, followed to
a very-small-Reynolds-number Stokes one.

Álvaro

2015-07-13 16:39 GMT+02:00 Adam Sierakowski <notifications@github.com>:

**Comment by asiera** [comment]
Hi Álvaro,

I've pushed a new change to the master branch that provides the option to compile with **theoretical** zero-Reynolds number Stokes flow. To use this, simply do a `make clean; make stokes`. This means that, no matter what is going on inside your simulation, there is no convective term being solved and you have true Stokes flow.

If instead you want very-small-Reynolds-number instead, you should *not* use the `stokes` option, but instead solve the full Navier-Stokes equations with the convective term. In this case, you'll have to ensure that what is going on inside your simulation is small/slow/viscous enough that you have the desired Stokes flow.

***Disclaimer***
I have not done any validation with Stokes flow, and thus cannot provide any assurance of the accuracy of the results. It is well known that projection methods can be susceptible to a splitting error proportional to \Delta t / Re---though I believe the formulation that we use does not suffer from this error---and this can cause some pretty big problems for these simulations.

That being said, I strongly encourage you to run some simple tests (such as a single stationary particle in the center of a large domain) to prove that you're getting results for quantities like drag force that match the theoretical expectations. If you perform any tests, please share them with me. I'd like to know whether I can avoid having to give this disclaimer in the future.

Cheers,

Adam

**Comment by asiera** [comment]
Hi Álvaro,

I hope you have had some luck with this. Since I haven't heard back, I'm assuming things are working properly, so I'm closing the issue.

Adam
