### ISSUE TITLE
Finished simulation does not end itself

### ISSUE THREAD

**Issue by dwille** [groundcherry/bluebottle#40]
If a simulation reaches its duration, it does not finish cleanly -- rather, it keeps submitting a restart request.

**Comment by dwille** [comment]
Restart capability also does not seem to be recognizing new inputs -- if duration is increased, this does not register in the simulation

**Comment by dwille** [comment]
Note: cannot replicate on `lucan`

**Comment by asiera** [comment]
Darn right it does!

**Comment by dwille** [comment]
Note: cannot replicate second bug on `lucan` -- program correctly reads the new input

**Comment by dwille** [comment]
...dafuq?

**Comment by asiera** [comment]
Hm.

**Comment by dwille** [comment]
Okay, this is odd. According to the bbottle.out file, nothing ran. According to `ls output/part-*`, the simulation ran like it was supposed to, including recognizing the duration change in the input file. I guess it just never printed the information to `stdout` for some reason. This issue did not occur with 6 other cases that were treated the exact same way.

**Comment by asiera** [comment]
So false alarm?

**Comment by dwille** [comment]
Looking at the bbottle.out file, it goes to the first end time, then runs ~25,000 times without doing anything (4 days), then starts up from again and keeps chugging along. 

I'm not sure what type of alarm it is....

**Comment by asiera** [comment]
We've seen MARCC's SLURM do other strange things as well. Think we can blame it on that?

**Comment by dwille** [comment]
I think so. It's a little worrisome that it ran for three days without generating any data, then decided it was going to start working again. I'll survive. Marking as closed, but at least we have a record of the behavior.

**Comment by dwille** [comment]
Also occurs at the end of some simulations -- reaches duration, and continues submitting useless jobs. Priority = low, since it only requires a little bit of user intelligence to realize that a job is resubmitting every 15 seconds

**Comment by asiera** [comment]
But only on MARCC?

**Comment by dwille** [comment]
As far as I can tell.. need to do some testing to find out how to replicate this.

**Comment by asiera** [comment]
Keep me updated.

**Comment by dwille** [comment]
New "feature" -- 
> `10163 terminate called after throwing an instance of 'thrust::system::detail::bad_alloc'`
> `10164   what():  std::bad_alloc: an illegal memory access was encountered`
is thrown, simulation ends, but the dependency does not.

**Comment by asiera** [comment]
Should this be a separate issue?

**Comment by dwille** [comment]
Not sure. The two issues could have the same root cause.

**Comment by asiera** [comment]
On MARCC, the dependencies never disappear. Is that the behavior here?

**Comment by dwille** [comment]
Yes:
> `srun: error: gpu025: task 0: Segmentation fault`
> `srun: Terminating job step 1072949` (current job)
> `srun: Submitted batch job 1073723`
>
> `Running bluebottle_0.1`

... et. cetera. So the dependency never realizes that the master job failed, and continues on its merry way.

**Comment by asiera** [comment]
So it seems that the dependency doesn't care what exit code Bluebottle throws upon exit. That's something on MARCC's side and Bluebottle.

**Comment by asiera** [comment]
That could also explain why it doesn't send emails properly. We have it set up to email if `FAIL`, but it doesn't respect an `EXIT_FAILURE`.

**Comment by asiera** [comment]
Although this only happens to you, as far as I know. No one else has mentioned encountering this problem. Can you double-check your `build-restart.sh` submission script and make sure the `#SBATCH --dependency=afterok:$2` is working properly?

**Comment by dwille** [comment]
Not sure how to test if it's working properly, but that is how it's written in the file

**Comment by asiera** [comment]
Throw together a short program that prints something and then returns `EXIT_FAILURE` to see if MARCC does what it is supposed to.

**Comment by dwille** [comment]
Can you "assign" this to me?

**Comment by ajsierakowski** [comment]
Fixed in f51301bd4aa492f3489cd402101d5e63ce6d989b
